# Install course requirements
# cd into this directory and run.
# `brew bundle`

tap "homebrew/bundle"
tap "homebrew/core"

brew "checkov" # IaC policy check https://checkov.io
brew "cloud-nuke" # Destroyer of clouds.
brew "graphviz" # Graph visualizer
brew "make" # Makefile processor
brew "pre-commit" # Pre-commit static analysis
brew "terraform-docs" # Automatic documentation for Terraform modules
brew "terragrunt" # Terraform preprocessor to keep configs DRY.
brew "tfenv" # Terraform version manager
brew "tflint" # Terraform linter
brew "kreuzwerker/taps/m1-terraform-provider-helper" # For m1 Mac compat.