iAWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

    CrudHandler:
        Type: AWS::Serverless::Function
        Properties:
           Runtime: python3.6
           Handler: app.entrypoint
           Events:
             Getagency:
               Type: Api
               Properties:
                 Path: /agency/{aId}
                 Method: get
             GetquestionResponses:
               Type: Api
               Properties:
                 Path: /questionResponses/{aId}
                 Method: get
             Getquestions:
               Type: Api
               Properties:
                 Path: /questions/{aId}
                 Method: get
             Gettopics:
               Type: Api
               Properties:
                 Path: /topics/{aId}
                 Method: get
             Getresponses:
               Type: Api
               Properties:
                 Path: /responses/{aId}
                 Method: get
             GetresponsesMetadata:
               Type: Api
               Properties:
                 Path: /responsesMetadata/{aId}
                 Method: get
           
           Environment:
             Variables:
              AGENCY_TABLE_ID:
              LOGLEVEL:
